- app/controllers/about_controller.rb
- app/controllers/admin/media_downloads_controller.rb
- app/models/media_download.rb
- app/views/about/_media_download.html.erb
- app/views/about/index.html.erb
- app/views/admin/base/index.html.erb
- app/views/admin/media_downloads/_form.html.erb
- app/views/admin/media_downloads/_media_download.html.erb
- app/views/admin/media_downloads/edit.html.erb
- app/views/admin/media_downloads/index.html.erb
- app/views/admin/media_downloads/new.html.erb
- config/locales/views/about/en.yml
- config/routes.rb
- db/migrate/20170129041117_create_media_downloads.rb
- db/schema.rb
- test/controllers/admin/media_downloads_controller_test.rb
- test/fixtures/media_downloads.yml
- test/models/media_download_test.rb
Initial implementation of the Marketing media library on the About page.
> Media Library

- app/assets/stylesheets/base.scss
- app/assets/stylesheets/modules/article.scss
- app/assets/stylesheets/modules/news.scss
- app/views/application/_flash.html.erb
- app/views/application/_related_article.html.erb
- app/views/articles/show.html.erb
- app/views/training/index.html.erb
Changes styles to work with the text editor for images and blockquotes
> Eh articles training

- app/models/concerns/taggable.rb
- app/services/marketing_content_filter.rb
- app/views/application/_related_blog_post.html.erb
- app/views/application/_related_case_study.html.erb
- app/views/articles/show.html.erb
- test/services/marketing_content_filter_test.rb
This fixes returns of `nil` breaking pages.
> Fix marketing content filter bug

- app/views/admin/products/_form.html.erb
Marketing needs the text edit in products
> added text edit in products form

- app/assets/stylesheets/modules/article.scss
- app/views/products/show.html.erb
Marketing needed to add bullets in products (though they don't like how it looks so it may change again later, but for now they want it)
> text bullets in products

- app/controllers/training_courses_controller.rb
- app/views/admin/training_courses/_form.html.erb
- test/controllers/training_courses_controller_test.rb
- test/controllers/training_event_requests_controller_test.rb
- test/fixtures/training_courses.yml
Fix some small error with training courses from not being created.
> Training events

- app/assets/javascripts/knowledge_base_articles.js
- app/assets/stylesheets/modules/article.scss
- app/assets/stylesheets/modules/knowledge-base.scss
- app/assets/stylesheets/modules/news.scss
- app/assets/stylesheets/modules/products.scss
- app/controllers/knowledge_base_articles_controller.rb
- app/views/admin/base/_site_footer.html.erb
- app/views/application/_site_footer.html.erb
- app/views/knowledge_base_articles/show.html.erb
- app/views/knowledge_base_articles/vote.js.erb
- config/routes.rb
spacing issue on click pages wanted to be changed by marketing
> click spacing

- app/assets/stylesheets/modules/results.scss
- app/controllers/results_controller.rb
- app/models/article.rb
- app/models/blog_post.rb
- app/models/product.rb
- app/models/result.rb
- app/models/return_material_authorization_policy_document.rb
- app/views/application/_site_header.html.erb
- app/views/results/index.html.erb
- config/routes.rb
🛠  migration needed
Site wide search done.
Searches: Product, Dealers, Knowledge Base Articles, Case Studies, Blog Posts and Legal.
> site wide search

- app/assets/javascripts/admin/training_events.js
- app/assets/stylesheets/modules/enrollment.scss
- app/models/training_event_course.rb
- app/views/enrollments/index.html.erb
- app/views/training_events/_form.html.erb
This merge request fixed a javascript error (in training_events.js) that was causing to precompiled assets to fail.
This request also finishes up all the front end work requirements, that is required to this point.
> Jc training events

- app/controllers/admin/knowledge_base_articles_controller.rb
- app/views/admin/knowledge_base_articles/_form.html.erb
knowledge autocomplete for tagging.
> kb autocomplete for tagging added

- app/models/concerns/taggable.rb
- test/models/concerns/taggable_test.rb
#138 @partydrone the issue with the test was article was rolling back because the date was in quotes ''.  So you might want to make sure your tests are working right.  I will also check that as well
> Jc tag bug

- app/views/application/_site_header.html.erb
> fixes #147

- app/assets/javascripts/support_langauge_filter.js
- app/models/download.rb
- app/views/products/_download.html.erb
- app/views/products/show.html.erb
- config/initializers/i18n.rb
This pull request filters download content by languages based on select options drop-down.  Items are also sorted by the 'en' locale first  with title ascending and all other locales 2nd title ascending
Closes #67.
> Jc order downloads

- app/assets/stylesheets/modules/training.scss
- app/controllers/admin/training_events_controller.rb
- app/views/admin/training_events/_form.html.erb
- app/views/admin/training_events/_training_event.html.erb
- app/views/admin/training_events/index.html.erb
- app/views/admin/training_events/show.html.erb
- app/views/training_events/_form.html.erb
- app/views/training_events/_training_event.html.erb
- app/views/training_events/index.html.erb
- app/views/training_events/show.html.erb
- db/migrate/20170523222138_add_host_to_training_events.rb
- db/schema.rb
> Jc training event fixes

- app/views/products/show.html.erb
> removed the view more

- app/assets/stylesheets/modules/legal.scss
- app/views/admin/base/index.html.erb
- app/views/features/show.html.erb
- config/initializers/refile.rb
> Add features to related stories

- app/models/download.rb
- app/models/knowledge_base_article.rb
- app/models/legal_policy_document.rb
Fixes #212 
- added search to legal, downloads and knowledge base articles
> fixes #212

- app/assets/javascripts/home.js
- app/views/application/_site_header.html.erb
The issue with this was because css was revealing the search input field it was taking focus away from the search field.
So to combat this visual effect, I added a set timeout that waits half a second then sets the focus.
> added logic for focus in seach input

- app/assets/stylesheets/modules/home.scss
> homepage alignment

- app/controllers/products_controller.rb
- app/models/product.rb
- app/models/product_category.rb
- app/models/product_type.rb
- app/views/product_categories/_product_category.html.erb
- app/views/product_types/_product_type.html.erb
- app/views/products/_product_category.html.erb
- test/models/product_category_test.rb
> Hide product categories and product types with no active products

- app/assets/stylesheets/modules/training.scss
> training css issue

- app/assets/stylesheets/modules/about.scss
- app/views/about/index.html.erb
- app/views/media_downloads/_media_download.html.erb
- config/locales/views/about/en.yml
just some text and css changes
The text changes were requested by marketing to match the submenu on top.
> media library updates

- app/views/training_events/index.html.erb
Fixes #239 
-Adds text if there are no training events to be shown
-
-
> fixes #239

- app/controllers/admin/products_controller.rb
- app/models/product.rb
- app/models/product_category.rb
- app/views/admin/base/_site_header.html.erb
- app/views/admin/products/_form.html.erb
- config/locales/models/product/en.yml
- db/migrate/20170619170540_add_matured_on_to_products.rb
- db/schema.rb
- test/fixtures/products.yml
- test/models/product_test.rb
Fixes #
- Add a maturation date to products
> Add maturation to products

- app/views/site_mailer/demo_request.html.erb
- app/views/site_mailer/demo_request.text.erb
> Add email address to demo request message
